---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: slug
  type: text
  config:
    required: true
  label: Slug
- name: feature
  type: file
  config:
    maxSize: 1
  label: Feature
- name: video
  type: text
  config:
    required: false
  label: Video
  description: URL to youtube video.
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: Body
- name: images
  type: image_gallery
  config: {}
  label: Images
pages:
- content/projects/darth-vader.yaml
