---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: slug
  type: text
  config:
    required: true
  label: Slug
- name: type
  type: select
  default: motion
  config:
    required: true
    options:
    - motion
    - web
    - design
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: feature
  type: file
  config:
    maxSize: 1
  label: Feature
- name: video
  type: text
  config:
    required: false
  label: Video
  description: URL to vimeo video.
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: Body
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: iframe
  type: text
  config:
    required: false
  label: iFrame
  description: Link to another site to be displayed
pages:
- content/projects/chess.yaml
- content/projects/darth-vader-1.yaml
- content/projects/darth-vader.yaml
- content/projects/dice.yaml
