---
label: Project
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: slug
  type: text
  config:
    required: true
  label: Slug
- name: type
  type: select
  default: motion
  config:
    required: true
    options:
    - motion
    - web
    - design
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- name: feature
  type: file
  config:
    maxSize: 1
  label: Feature
- name: video
  type: text
  config:
    required: false
  label: Video
  description: URL to vimeo video.
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: Body
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: iframe
  type: text
  config:
    required: false
  label: iFrame
  description: Link to another site to be displayed
- name: codePen
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Code Pen
pages:
- content/projects/adventures-app.yaml
- content/projects/ansto.yaml
- content/projects/astronaut.yaml
- content/projects/calculator.yaml
- content/projects/chess.yaml
- content/projects/cobox.yaml
- content/projects/dating-app.yaml
- content/projects/dice.yaml
- content/projects/fightclub.yaml
- content/projects/finder.yaml
- content/projects/good-return.yaml
- content/projects/my-website.yaml
- content/projects/rivalry.yaml
- content/projects/showreel.yaml
- content/projects/video-database.yaml
- content/projects/video-player.yaml
- content/projects/wet-warm-dribble.yaml
- content/projects/wikipedia-redesign.yaml
- content/projects/zach-s-ceremony.yaml
